name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs only when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build Spring Boot JAR (skip tests if needed)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Run unit tests (optional)
      - name: Run Tests
        run: mvn test

      # Step 5: Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-ci-demo-app:latest .

      # Step 6: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Push Docker image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-ci-demo-app:latest
